"use client";

import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/ui/accordion";

const FAQ_LIST = [
  {
    id: "q1",
    question: "How does CalmHive help me stay focused?",
    answer:
      "CalmHive helps you stay focused by breaking your work into manageable tasks, offering personalized plans, and giving weekly insights so you can see where your time goes and improve over time.",
  },
  {
    id: "q2",
    question: "What is the onboarding process like?",
    answer:
      "Onboarding is an AI-driven, conversational flow made of short, skippable questions. Responses are stored in your account and used to personalize your weekly plan.",
  },
  {
    id: "q3",
    question: "How does AI generate my weekly plan?",
    answer:
      "The plan is created from your onboarding responses, preferences, and available capacity. Plans are lightweight, flexible, and tailored to your routine.",
  },
  {
    id: "q4",
    question: "Can I edit or customize my plan?",
    answer:
      "Yes — you can edit tasks manually or use the AI assistant on the Plan screen to propose changes. AI suggestions require your confirmation before being applied.",
  },
  {
    id: "q5",
    question: "What are Weekly Insights and how often will I get them?",
    answer:
      "Weekly Insights are gentle summaries generated by a cron job (runs weekly). You’ll receive a short in-app summary and an optional weekly email with reflective suggestions.",
  },
  {
    id: "q6",
    question: "How is my data protected?",
    answer:
      "We follow industry best practices to secure your data, including encrypted storage, least-privilege access, and regular audits. Sensitive data is never shared without your consent.",
  },
  {
    id: "q8",
    question: "How does journaling work and is it private?",
    answer:
      "Journaling is guided and AI-assisted. Drafts are generated for you to edit and save; raw text is never quoted, and only aggregated signals are stored for insights.",
  },
];

export default function FAQ() {
  return (
    <section
      id="faq"
      className="my-16 py-16 bg-white/80 backdrop-blur-sm rounded-2xl mx-auto"
    >
      <div className="max-w-7xl mx-auto px-6 lg:px-24">
        <div className="text-center max-w-4xl mx-auto">
          <h3 className="text-3xl font-semibold text-[var(--ch-sage-dark)]">
            Frequently Asked Questions
          </h3>
          <p className="mt-4 text-base text-muted-foreground">
            Got a question? We’ve compiled the most common questions about
            CalmHive.
          </p>
        </div>
      </div>

      <div className="mt-8 max-w-[90vw] mx-auto px-4 lg:px-0">
        <Accordion type="single" collapsible>
          {FAQ_LIST.map((f) => (
            <AccordionItem key={f.id} value={f.id} className="border-b py-6">
              <AccordionTrigger className="text-lg  font-medium py-2">
                {f.question}
              </AccordionTrigger>
              <AccordionContent className="text-base text-muted-foreground py-2">
                {f.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
