"use client";

import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/ui/accordion";

export default function FAQ() {
  return (
    <section
      id="faq"
      className="max-w-6xl mx-auto my-16 px-6  bg-white/80 backdrop-blur-sm rounded-2xl"
    >
      <div className="max-w-6xl mx-auto text-center">
        <h3 className="text-2xl font-semibold text-[var(--ch-sage-dark)]">
          Frequently Asked Questions
        </h3>
        <p className="mt-3 text-sm text-muted-foreground">
          Got a question? We’ve compiled the most common questions about
          CalmHive.
        </p>
      </div>

      <div className="mt-8 max-w-3xl mx-auto">
        <Accordion type="single" collapsible>
          <AccordionItem value="q1" className="border-b">
            <AccordionTrigger>
              How does CalmHive help me stay focused?
            </AccordionTrigger>
            <AccordionContent>
              CalmHive helps you stay focused by breaking your work into
              manageable tasks, offering personalized plans, and giving weekly
              insights so you can see where your time goes and improve over
              time.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="q2" className="border-b">
            <AccordionTrigger>
              What is the onboarding process like?
            </AccordionTrigger>
            <AccordionContent>
              Onboarding is an AI-driven, conversational flow made of short,
              skippable questions. Responses are stored in your account and used
              to personalize your weekly plan.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="q3" className="border-b">
            <AccordionTrigger>
              How does AI generate my weekly plan?
            </AccordionTrigger>
            <AccordionContent>
              The plan is created from your onboarding responses, preferences,
              and available capacity. Plans are lightweight, flexible, and
              tailored to your routine.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="q4" className="border-b">
            <AccordionTrigger>
              Can I edit or customize my plan?
            </AccordionTrigger>
            <AccordionContent>
              Yes — you can edit tasks manually or use the AI assistant on the
              Plan screen to propose changes. AI suggestions require your
              confirmation before being applied.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="q5" className="border-b">
            <AccordionTrigger>
              What are Weekly Insights and how often will I get them?
            </AccordionTrigger>
            <AccordionContent>
              Weekly Insights are gentle summaries generated by a cron job (runs
              weekly). You’ll receive a short in-app summary and an optional
              weekly email with reflective suggestions.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="q6" className="border-b">
            <AccordionTrigger>How is my data protected?</AccordionTrigger>
            <AccordionContent>
              We follow industry best practices to secure your data, including
              encrypted storage, least-privilege access, and regular audits.
              Sensitive data is never shared without your consent.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="q8" className="border-b">
            <AccordionTrigger>
              How does journaling work and is it private?
            </AccordionTrigger>
            <AccordionContent>
              Journaling is guided and AI-assisted. Drafts are generated for you
              to edit and save; raw text is never quoted, and only aggregated
              signals are stored for insights.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </section>
  );
}
